configs/openmrs_config/patientidentifiertypes/cambodia-identifiers.csv
https://issues.openmrs.org/browse/KH-68
=> KH-68: Add Passport No as extra ID during registration

README.md
=> Fix typo in READ.md file

configs/openmrs_config/concepts/assessment.csv
https://issues.openmrs.org/browse/KH-66
=> KH-66: Numeric concepts to display the units as part of the name

configs/openmrs_config/personattributetypes/personattributetypes.csv
https://issues.openmrs.org/browse/KH-83
=> KH-83: Rename  Social status to Marital status

configs/openmrs_config/globalproperties/address-template.xml
https://issues.openmrs.org/browse/KH-56
=> KH-56: Set default the country to Cambodia in Address Entry

configs/openmrs_config/concepts/education.csv, configs/openmrs_config/personattributetypes/personattributetypes.csv, configs/ozone_config/frontend/ozone-frontend-config.json
https://issues.openmrs.org/browse/KH-73
=> KH-73: Add Education entry at registration and fix merge conflict

configs/openmrs_config/visittypes/visittypes.csv
https://issues.openmrs.org/browse/KH-60
- I Closed the initial PR and this is a new one with the changes of the previous one
=> KH-60: Add a Cervical Cancer Screening Visit Type

configs/openmrs_config/concepts/occupation.csv
https://issues.openmrs.org/browse/KH-82
=> KH-82: Add Occupation options

configs/openmrs_config/patientidentifiertypes/cambodia-identifiers.csv
https://issues.openmrs.org/browse/KH-89
=> KH-89: Remove ID card

configs/ozone_config/frontend/ozone-frontend-config.json
Refer to [KH-85](https://issues.openmrs.org/browse/KH-85)
=> KH-85: National ID should show as default, and above IDPoor

configs/openmrs_config/ampathforms/adult_NCD_Consultation.json
https://issues.openmrs.org/browse/KH-105
=> KH-105: Add HbA1c test under Blood sugar levels in 'NCD Consultation form'

configs/openmrs_config/ampathforms/health_center_NCD_Screening.json, configs/openmrs_config/concepts/labs.csv
https://issues.openmrs.org/browse/KH-114
=> KH-114: Add 'Hb1AC' and 'OGTT' tests to Health Center - NCD Screening form

configs/openmrs_config/ampathforms/NCD_Consultation.json, configs/openmrs_config/ampathforms/NCD_Medical_History.json, configs/openmrs_config/ampathforms/NCD_Screening.json, configs/openmrs_config/ampathformstranslations/Health Center - NCD Screening_translations_km.json, configs/openmrs_config/ampathformstranslations/NCD Consultation_translations_km.json, configs/openmrs_config/ampathformstranslations/NCD Medical History_translations_km.json, start-distro.sh
As per ticket: https://issues.openmrs.org/browse/KH-20
=> KH-20: Localize form labels and form names

configs/openmrs_config/ampathforms/NCD_Consultation.json, configs/openmrs_config/concepts/past_medical_history.csv
Link to ticket [here](https://issues.openmrs.org/browse/KH-103)
=> KH-103: Add answers to TB Symptoms question in NCD Consultation Form

configs/ozone_config/frontend/ozone-frontend-config.json
https://issues.openmrs.org/browse/KH-152
=> KH-152: Address levels in Patient banner to show correct labels

configs/ozone_config/frontend/ozone-frontend-config.json
Refer to [KH-137](https://issues.openmrs.org/browse/KH-137)
=> KH-137: Patient registration→Add new section for Additional information

configs/openmrs_config/concepts/occupation.csv
Refer to this Jira [comment](https://issues.openmrs.org/browse/KH-137?focusedCommentId=288751&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-288751).
=> Fixed bug that fails answers in occupation field to load

configs/openmrs_config/ampathforms/NCD_Medical_History.json, configs/openmrs_config/concepts/past_medical_history.csv
Refer to [KH-163](https://issues.openmrs.org/browse/KH-163)
=> KH-163: Add questions about heart & kidney failures in medical history form

configs/openmrs_config/ampathforms/NCD_Consultation.json, configs/openmrs_config/ampathforms/NCD_Screening.json, configs/openmrs_config/ampathforms/cervical_cancer_screening.json, configs/openmrs_config/concepts/locations.csv, configs/openmrs_config/locations/locations.csv
https://issues.openmrs.org/browse/KH-159
=> KH-159: Fix Referral centers

configs/openmrs_config/ampathforms/NCD_Consultation.json
Refer to [KH-172](https://issues.openmrs.org/browse/KH-172)
=> KH-172: Add follow up date in NCD Consultation form

configs/openmrs_config/ampathforms/NCD_Medical_History.json
Refer to [KH-160](https://issues.openmrs.org/browse/KH-160)
=> KH-160: Hide questions if no previous DM in NCD Medical History form

configs/openmrs_config/ampathforms/NCD_Consultation.json, configs/openmrs_config/concepts/general.csv
Concept creation is conflicting with one from OCL
=> Fix 'Abnormal' concept references

configs/openmrs_config/ampathforms/NCD_Consultation.json, configs/openmrs_config/ampathforms/NCD_Screening.json, configs/openmrs_config/concepts/labs.csv
Link to ticket [here ](https://issues.openmrs.org/browse/KH-115)
=> KH-115: Add and adjust ranges for numeric values

configs/openmrs_config/ampathforms/cervical_cancer_screening.json
Refer to the Jira [comment](https://issues.openmrs.org/browse/KH-150?focusedCommentId=289004&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-289004)
[Treatment.webm](https://user-images.githubusercontent.com/38831673/234743585-c61a040f-b71c-4984-b50b-ba0345ca69ce.webm)
=> KH-150: Add concept uuid for Thermo-ablation device

configs/openmrs_config/ampathforms/NCD_Consultation.json
Refer to the [Jira](https://issues.openmrs.org/browse/KH-171?focusedCommentId=289057&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-289057) comment.
=> KH-171: Add missing concept uuid for cardiovacscular Exam

configs/openmrs_config/concepts/ethnicities.csv, configs/openmrs_config/concepts/general.csv, configs/openmrs_config/concepts/occupation.csv
Refer to [KH-157](https://issues.openmrs.org/browse/KH-157)
=> KH-157: Move 'Other' concept to general.csv file

configs/openmrs_config/ampathforms/NCD_Screening.json
Link to ticket [here](https://issues.openmrs.org/browse/KH-181)
=> KH-181: Add drop down list for drugs in HC NCD Screening form under the Management Section

configs/openmrs_config/ampathforms/NCD_Screening.json, configs/openmrs_config/concepts/general.csv
Link to ticket [here](https://issues.openmrs.org/browse/KH-182)
=> KH-182: Add questions about the type of user in HC-NCD Screening form

configs/openmrs_config/concepts/general.csv
Link to ticket [here](https://issues.openmrs.org/browse/KH-182)
=> KH-182: Add Khmer translation for Tele-consultation with NCD Unit:

configs/openmrs_config/ampathforms/NCD_Screening.json
Refer to [KH-187](https://issues.openmrs.org/browse/KH-187)
=> KH-187: HC Screening Form - Remove referral question in Assessment section

configs/openmrs_config/ampathforms/NCD_Screening.json
Refer to [KH-184](https://issues.openmrs.org/browse/KH-184)
[footExamination.webm](https://github.com/openmrs/ozone-distro-cambodia/assets/38831673/09085831-45c5-4118-b7d6-e8046fbed96c)
=> KH-184: Move the foot exam question below the tele consultation

configs/openmrs_config/globalproperties/i18n.xml
Link to ticket [here](https://mekomsolutions.atlassian.net/browse/KH-215)
=> Set default locale to Khmer (km)

configs/openmrs_config/ampathforms/NCD_Screening.json
Link to ticket [here](https://mekomsolutions.atlassian.net/browse/KH-245)
=> KH-245: Change Diagnoses answer from Unknown to None In NCD Screening form

configs/openmrs_config/ampathforms/NCD_Screening.json, configs/openmrs_config/concepts/lifestyle.csv
Link to ticket [here](https://mekomsolutions.atlassian.net/browse/KH-244)
=> KH-244: Add Year for quitting smoking in NCD Screening form

configs/ozone_config/frontend/ozone-frontend-config.json
Link to ticket [here](https://mekomsolutions.atlassian.net/browse/KH-238)
=> KH-238: Remove middle name from registration form

configs/openmrs_config/ampathforms/NCD_Screening.json
Ticket →  [KH-257](https://mekomsolutions.atlassian.net/browse/KH-257)
[Management.webm](https://github.com/openmrs/ozone-distro-cambodia/assets/38831673/a3a8ca78-25e0-44c8-b98f-ea8e20930c2c)
=> KH-257: Modify Management section of HC NCD screening form

configs/openmrs_config/concepts/opdConsultationReportConcepts.csv, configs/openmrs_config/jsonkeyvalues/opdConsultationReportConfig.json
Ticket: https://mekomsolutions.atlassian.net/browse/KH-256
=> KH-256: Activate HC1 report

configs/openmrs_config/jsonkeyvalues/opdConsultationReportConfig.json
Ticket: https://mekomsolutions.atlassian.net/browse/KH-256
=> KH-256: Typo correction

configs/openmrs_config/ampathforms/NCD_Screening.json
Ticket ID: [KH-247](https://mekomsolutions.atlassian.net/browse/KH-247)
[management.webm](https://github.com/openmrs/ozone-distro-cambodia/assets/38831673/844a5bba-2052-4810-9e95-89368cc1bdd6)
=> KH-247: Remove discharge reason in NCD Screening form

configs/ozone_config/frontend/ozone-frontend-config.json
Link to ticket [here](https://mekomsolutions.atlassian.net/browse/KH-246)
=> KH-246: Set to show family name first then first name

configs/ozone_config/frontend/ozone-frontend-config.json
Link to ticket [here](https://mekomsolutions.atlassian.net/browse/KH-254)
=> KH-254: Make visit punctuality optional

configs/openmrs_config/visittypes/visittypes.csv
Link to ticket [here](https://mekomsolutions.atlassian.net/browse/KH-231)
=> KH-231: Add a CC follow up visit type and rename the existing CC visit type to CC New Visit

configs/openmrs_config/concepts/education.csv
Ticket → [KH-240](https://mekomsolutions.atlassian.net/browse/KH-240)
=> KH-240: Add correct translation for the term Illiterate

configs/openmrs_config/concepts/past_medical_history.csv
Ticket → [KH-258](https://mekomsolutions.atlassian.net/browse/KH-258)
Description → Added a missing translation for the word Other health conditions
=> KH-258: Add translation for the word Other health conditions

configs/openmrs_config/concepts/sexual_orientation.csv, configs/openmrs_config/personattributetypes/personattributetypes.csv, configs/ozone_config/frontend/ozone-frontend-config.json
Ticket [KH-250](https://mekomsolutions.atlassian.net/browse/KH-250)
[patientRegistration.webm](https://github.com/openmrs/ozone-distro-cambodia/assets/38831673/8045c4f1-8f10-412f-8816-d2004d0711fc)
=> KH-250: Add gender question and answers

configs/openmrs_config/concepts/sexual_orientation.csv, configs/openmrs_config/personattributetypes/personattributetypes.csv
Ticket → [KH-250](https://mekomsolutions.atlassian.net/browse/KH-250)
[Registration.webm](https://github.com/openmrs/ozone-distro-cambodia/assets/38831673/2f3acff2-6bf3-4e95-84cc-284d939f983a)
=> KH-250: Add missing translations for sexual orientation concepts

configs/openmrs_config/ampathforms/NCD_Consultation.json, configs/openmrs_config/ampathforms/NCD_Screening.json, configs/openmrs_config/ampathforms/cervical_cancer_screening.json, configs/openmrs_config/ampathformstranslations/Health Center - NCD Screening_translations_km.json, configs/openmrs_config/encountertypes/encountertypes.csv
This reverts commit 5a52bdec724f441d9a2c9659ff91036f61eeec7b.
=> Revert "KH-222: Better consistency in form naming (#125)"

configs/ozone_config/frontend/ozone-frontend-config.json
Ticket → [KH-261](https://mekomsolutions.atlassian.net/browse/KH-261)
[registrationForm.webm](https://github.com/openmrs/ozone-distro-cambodia/assets/38831673/17cc043b-34fd-44fc-9325-5bb03dc7f6c1)
=> KH-261: Remove question for known patient from the registration form

prod/pom.xml
Reverts openmrs/ozone-distro-cambodia#179
=> Revert "Release 1.2.1"

README.md
Ticket → [KH-283](https://mekomsolutions.atlassian.net/browse/KH-283)
=> KH-283: Add release notes for version 1.2.0 and 1.2.2

README.md, configs/openmrs_config/ampathforms/NCD_Consultation.json
Link to ticket [here](https://mekomsolutions.atlassian.net/browse/KH-303)
=> KH-303: Add Year for quitting smoking to NCD Consultation form

README.md
Ticket → [KH-330](https://mekomsolutions.atlassian.net/browse/KH-330)
=> KH-330: Add release notes for version 1.2.3

configs/ozone_config/frontend/ozone-frontend-config.json
Link to ticket [here](https://mekomsolutions.atlassian.net/browse/KH-310)
=> KH-310: Add km translation for 'Select an option' in patient registration form 

configs/openmrs_config/ampathforms/cervical_cancer_screening.json, configs/openmrs_config/concepts/reproductive_history.csv
Link to ticket [here](https://mekomsolutions.atlassian.net/browse/KH-334)
=> KH-334: Add follow-up date for breast cancer screening in Cervical Cancer Screening Form

configs/openmrs_config/ampathforms/NCD_Consultation.json, configs/openmrs_config/ampathforms/NCD_Screening.json, configs/openmrs_config/ampathforms/cervical_cancer_screening.json, configs/openmrs_config/ampathformstranslations/NCD Screening_translations_en.json, configs/openmrs_config/ampathformstranslations/NCD Screening_translations_km.json, configs/openmrs_config/encountertypes/encountertypes.csv
Ticket → [KH-222](https://mekomsolutions.atlassian.net/browse/KH-222)
=> KH-222: Better consistency in form naming

configs/openmrs_config/ampathforms/NCD_Consultation.json, configs/openmrs_config/ampathforms/NCD_Screening.json, configs/openmrs_config/ampathforms/cervical_cancer_screening.json, configs/openmrs_config/ampathformstranslations/Health Center - NCD Screening_translations_en.json, configs/openmrs_config/ampathformstranslations/Health Center - NCD Screening_translations_km.json, configs/openmrs_config/encountertypes/encountertypes.csv
Reverts openmrs/ozone-distro-cambodia#186
=> Revert "KH-222: Better consistency in form naming"

configs/openmrs_config/locations/locations.csv
Link to ticket [here](https://mekomsolutions.atlassian.net/browse/KH-286)
=> KH-286: Allow location search to support Khmer and  English 

configs/ozone_config/frontend/ozone-frontend-config.json
Link to ticket [here](https://mekomsolutions.atlassian.net/browse/KH-348)
=> KH-348: Fix wrong Khmer translation for patient

configs/openmrs_config/ampathforms/NCD_Medical_History.json, configs/openmrs_config/ampathforms/NCD_Screening.json, configs/openmrs_config/concepts/past_medical_history.csv
Ticket → [KH-359](https://mekomsolutions.atlassian.net/browse/KH-359)
=> KH-359: Add question for screening diabetes & hypertension in Medical History form & NCD Screening form

README.md
Ticket → [KH-354](https://mekomsolutions.atlassian.net/browse/KH-354)
=> KH-354: Add release notes for version 1.3.0

README.md
Ticket → [KH-354](https://mekomsolutions.atlassian.net/browse/KH-354)
=> KH-354: Update release notes for version 1.3.0

configs/openmrs_config/ampathforms/cervical_cancer_screening.json
Link to ticket [here](https://mekomsolutions.atlassian.net/browse/KH-373)
=> KH-373: Move 'History of CC Screening page' to be the first page in the CC form

configs/openmrs_config/concepts/reproductive_history.csv
Link to ticket[ here](https://mekomsolutions.atlassian.net/browse/KH-377)
=> KH-377: Retire concept named 'STI'

configs/openmrs_config/concepts/reproductive_history.csv
Reverts openmrs/ozone-distro-cambodia#240
=> Revert "KH-377: Retire concept named 'STI'"

configs/ozone_config/frontend/ozone-frontend-config.json
=> KH-367: Disable changing Visit Location in the Start Visit form

configs/openmrs_config/ampathformstranslations/Health Center - NCD Screening_translations_en.json, configs/openmrs_config/ampathformstranslations/Health Center - NCD Screening_translations_km.json, configs/openmrs_config/encountertypes/encountertypes.csv
Ticket → [KH-222](https://mekomsolutions.atlassian.net/browse/KH-222)
[NCDScreeningForm.webm](https://github.com/openmrs/ozone-distro-cambodia/assets/38831673/64d0dad5-2ecc-47c3-90c0-76739702b0aa)
=> KH-222: Renamed 'Health Center-NCD Screening' to 'NCD Screening' form

configs/openmrs_config/ampathforms/NCD_Screening.json
Ticket → [KH-390](https://mekomsolutions.atlassian.net/browse/KH-390)
[Referral.webm](https://github.com/openmrs/ozone-distro-cambodia/assets/38831673/5ae82bd6-c54a-4c0c-8679-d36a92fa355a)
=> KH-390: Re-organized referral questions in NCD Screening form

configs/openmrs_config/ampathforms/NCD_Consultation.json, configs/openmrs_config/ampathforms/NCD_Screening.json
Link to ticket [here](https://mekomsolutions.atlassian.net/browse/KH-365)
=> KH-365: Create a link to the drug order basket

configs/openmrs_config/concepts/locations.csv
Referral facility names updated to the form Province > District > Facility Name
Link to the ticket: [KH-363](https://mekomsolutions.atlassian.net/jira/software/c/projects/OZ/boards/32?quickFilter=61&selectedIssue=KH-363)
=> (feat) KH-363: Locations names' updated to include province and district

configs/openmrs_config/ampathforms/NCD_Consultation.json, configs/openmrs_config/ampathforms/NCD_Screening.json, configs/openmrs_config/ampathforms/cervical_cancer_screening.json
Link to ticket [here](https://mekomsolutions.atlassian.net/browse/KH-297)
=> KH-297: Ability to search the health facility name in 'Referral to'

configs/openmrs_config/concepts/sexual_orientation.csv, configs/openmrs_config/personattributetypes/personattributetypes.csv, configs/ozone_config/frontend/ozone-frontend-config.json
Ticket → [KH-417](https://mekomsolutions.atlassian.net/browse/KH-417)
[OmittedSexualOrientation.webm](https://github.com/openmrs/ozone-distro-cambodia/assets/38831673/68a2f629-d449-4ca0-9726-61976bf0bc46)
=> KH-417: Removed sexual orientation question from patient registration form

configs/openmrs_config/ampathforms/NCD_Consultation.json, configs/openmrs_config/ampathforms/NCD_Screening.json, configs/openmrs_config/ampathforms/cervical_cancer_screening.json
Link to ticket [here](https://mekomsolutions.atlassian.net/browse/KH-416)
=> KH-416: Increment Clinical forms versions

configs/openmrs/initializer_config/ampathforms/NCD_Medical_History.json
Ticket → [KH-429](https://mekomsolutions.atlassian.net/browse/KH-429)
[MedicalHistoryForm.webm](https://github.com/openmrs/ozone-distro-cambodia/assets/38831673/6b6918f6-82cb-485f-aaca-e14ea323a1d9)
=> KH-429: Removed 'Have you been screened for Diabetes and Hypertension?' from NCD Medical History Form

configs/openmrs/frontend_config/ozone-frontend-config.json
Ticket → [KH-428](https://mekomsolutions.atlassian.net/browse/KH-428)
=> KH-428: Override Khmer translation for 'markDeceased'

configs/openmrs/initializer_config/ampathforms/NCD_Consultation.json, configs/openmrs/initializer_config/ampathforms/NCD_Screening.json
Link to the ticket: https://mekomsolutions.atlassian.net/browse/KH-455
=> KH-455: Added pre-diabetes under Other health condition

configs/openmrs/initializer_config/concepts/reproductive_history.csv
Ticket →  [KH-445](https://mekomsolutions.atlassian.net/browse/KH-445)
[NumberOfMiscourages.webm](https://github.com/openmrs/ozone-distro-cambodia/assets/38831673/77bff885-d75a-4aed-b756-ce81aeb4cf38)
=> KH-445: Updated translation for 'Number of miscarriages'

configs/openmrs/initializer_config/concepts/physical_examination.csv
Ticket → [KH-459](https://mekomsolutions.atlassian.net/browse/KH-459)
[FootExam.webm](https://github.com/openmrs/ozone-distro-cambodia/assets/38831673/7c1e4466-0687-460b-b1b4-4c495c1ed882)
=> KH-459: Updated translation for 'Foot exam problem' in NCD Screening form

configs/openmrs/initializer_config/concepts/reproductive_history.csv
Ticket → [KH-457](https://mekomsolutions.atlassian.net/browse/KH-457)
[SCJ.webm](https://github.com/openmrs/ozone-distro-cambodia/assets/38831673/7588679d-c5e2-442e-92a7-4781ac19c0fc)
=> KH-457: Updated translation for 'Visibility of SCJ' in Cervical Cancer Screening form

README.md
Ticket → [KH-471](https://mekomsolutions.atlassian.net/browse/KH-447)
=> KH-471: Added release notes for version 1.5.0

configs/openmrs/initializer_config/ampathforms/cervical_cancer_screening.json, configs/openmrs/initializer_config/concepts/reproductive_history.csv
Link to the ticket: https://mekomsolutions.atlassian.net/browse/KH-435
=> KH-435: Updated the 'Dont know' option to 'Test not done' in Cervical Cancer Screening form

configs/openmrs/initializer_config/ampathforms/cervical_cancer_screening.json
Link to ticket --> https://mekomsolutions.atlassian.net/browse/KH-442
=> KH-442: Move referral question to different section in Cervical Cancer Screening form

base/pom.xml
Ticket: https://mekomsolutions.atlassian.net/browse/KH-477
=> KH-477: Fixed Ozone to version 1.0.0-alpha.9.

configs/openmrs/frontend_config/ozone-frontend-config.json
Link to the ticket: https://mekomsolutions.atlassian.net/browse/KH-474
=> KH-474: Updated the translation for "Home"

README.md
Ticket → [KH-480](https://mekomsolutions.atlassian.net/browse/KH-480)
=> KH-480: Added release notes for version 1.6.0

base/pom.xml, configs/openmrs/initializer_config/jsonkeyvalues/opdConsultationReportConfig.json
TIcket: https://mekomsolutions.atlassian.net/browse/KH-392
=> KH-392: Override Common Reports Module with version 1.4.0

README.md, base/pom.xml, pom.xml, prod/pom.xml
Ticket: https://mekomsolutions.atlassian.net/browse/KH-477
=> Release 1.6.0

configs/openmrs/initializer_config/ampathforms/cervical_cancer_screening.json, configs/openmrs/initializer_config/concepts/reproductive_history.csv
Ticket → [KH-435](https://mekomsolutions.atlassian.net/browse/KH-435)
[HPVTest.webm](https://github.com/mekomsolutions/ozone-distro-cambodia/assets/38831673/1870f664-9a73-4832-8c68-244efbf34e3a)
[KH-435]: https://mekomsolutions.atlassian.net/browse/KH-435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KH-435: Added 'Unknown' option under HPV virus test in Cervical Cancer Screening form

base/pom.xml
Ticket: https://mekomsolutions.atlassian.net/browse/KH-482
=> KH-482: Bump Common Reports to 1.4.1

README.md
Ticket → [KH-480](https://mekomsolutions.atlassian.net/browse/KH-456)
[KH-480]: https://mekomsolutions.atlassian.net/browse/KH-480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KH-480: Added release notes for version 1.6.1

base/configs/openmrs/initializer_config/concepts/reproductive_history.csv
Ticket: https://mekomsolutions.atlassian.net/browse/KH-509
Attachments:
=> KH-509: Update question under Cancer section in CSS form

base/configs/openmrs/initializer_config/concepts/labs.csv
Ticket: https://mekomsolutions.atlassian.net/browse/KH-505
Attachment:
=> KH-505: Update translation for 'ACE inhibitor' in NCD Consultation form

base/configs/openmrs/initializer_config/ampathformstranslations/cervical_cancer_screening_km.json
Ticket: https://mekomsolutions.atlassian.net/browse/KH-551
Attachment:
=> KH-551: Update translation for Breast Cancer in CCS form

base/configs/openmrs/initializer_config/concepts/reproductive_history.csv
Ticket: https://mekomsolutions.atlassian.net/browse/KH-552
Attachment:
=> KH-552: Update translation for Abscesses in CCS form

base/configs/openmrs/initializer_config/concepts/general.csv
Ticket: https://mekomsolutions.atlassian.net/browse/KH-554
Attachment:
=> KH-554: Update translation for 'Tele-Consultation with NCD unit' in NCD Screening form

base/configs/openmrs/initializer_config/attributetypes/attribute_types.csv, base/configs/openmrs/initializer_config/concepts/general.csv
Ticket: https://mekomsolutions.atlassian.net/browse/KH-557
Attachments:
=> KH-557: Rename 'Insurance Type' to 'Payment type' in Start visit

base/configs/openmrs/frontend_config/ozone-frontend-config.json
Ticket: https://mekomsolutions.atlassian.net/browse/KH-553
Attachment:
[RegisterNewPatient.webm](https://github.com/mekomsolutions/ozone-distro-cambodia/assets/38831673/9b0d26b5-c024-4902-9e1f-8dbad2cf9f0d)
=> KH-553: Rename 'Create New Patient' to 'Register New Patient' in the Patient Registration

base/configs/openmrs/initializer_config/concepts/labs.csv
Ticket: https://mekomsolutions.atlassian.net/browse/KH-556
Attachments:
=> KH-556: Rename 'HbA1c' to 'HbA1c (optional)' in NCD Screening and NCD Consultation forms

base/configs/openmrs/frontend_config/ozone-frontend-config.json
**What does the PR do?**
- Fix config gender values to be lowercase.
[Screencast from 13-06-24 17_35_33 (1).webm](https://github.com/mekomsolutions/ozone-distro-cambodia/assets/53287480/3431c71b-3d49-4837-8c96-f53ccae42ba7)
=> Fix gender config values to lowercase

base/configs/superset/pom.xml, base/pom.xml
https://mekomsolutions.atlassian.net/browse/OZ-429
=> OZ-429: Fine tune the Superset configs packaging

README.md
Ticket: https://mekomsolutions.atlassian.net/browse/KH-565
=> KH-565: Added release notes for version 1.7.0

.github/workflows/ci.yml
- Triggers release on publish event.
=> INFRA-407: Trigger release on publish event

README.md, base/configs/superset/pom.xml, base/pom.xml, pom.xml, prod/pom.xml
Ticket: https://mekomsolutions.atlassian.net/browse/KH-564
=> Release Ozone Kh 1.7.0

base/configs/openmrs/frontend_assembly/spa-assemble-config.json
This PR updates the version of the Form entry app to include the latest changes from the @openmrs/ngx-formentry (Angular Form Engine)
=> Update the @openmrs/esm-form-entry-app to the latest version.

base/pom.xml
This PR upgrades Ozone Analytics queries to version 1.2.0.
=> Upgraded Ozone Analytics queries to v1.2.0

base/configs/openmrs/frontend_assembly/spa-assemble-config.json, base/pom.xml, base/scripts/openmrs/frontend_assembly/build-openmrs-frontend.groovy, prod/pom.xml
This PR Overrides OpenMRS frontend core version with `5.6.1-pre.1857`
=> Override build OpenMRS frontend script & use core version `5.6.1-pre.1857`

base/configs/openmrs/frontend_config/ozone-frontend-config.json
Follow up for: https://mekomsolutions.slack.com/archives/G421UNF5L/p1720521982317539?thread_ts=1720507603.243549&cid=G421UNF5L
=> Fixed Home translation key
